// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    jqInputFilter: function(options) {
      var bindEvent, log, settings;

      settings = {
        numberClass: 'numeric',
        integerClass: 'integer',
        posNumberClass: 'positive',
        posIntegerClass: 'positive-integer',
        debug: true
      };
      settings = $.extend(settings, options);
      bindEvent = function($el) {
        $el.on("keydown", "input." + settings.posNumberClass, function(e) {
          var val;

          if (!(e.which === 8 || e.which === 9 || e.which === 17 || e.which === 46 || (e.which >= 35 && e.which <= 40) || (e.which >= 48 && e.which <= 57) || (e.which >= 96 && e.which <= 105) || (e.which === 190) || (e.which === 110))) {
            e.preventDefault();
          }
          val = $(this).val();
          if ((e.which === 190 || e.which === 110) && (!val || /[\.]/g.test(val))) {
            return e.preventDefault();
          }
        });
        return $el.on("keydown", "input." + settings.posIntegerClass, function(e) {
          var val;

          if (!(e.which === 8 || e.which === 9 || e.which === 17 || e.which === 46 || (e.which >= 35 && e.which <= 40) || (e.which >= 48 && e.which <= 57) || (e.which >= 96 && e.which <= 105))) {
            e.preventDefault();
          }
          val = $(this).val();
          if ((e.which === 190 || e.which === 110) && (!val || /[\.]/g.test(val))) {
            return e.preventDefault();
          }
        });
      };
      log = function(msg) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
        }
      };
      return this.each(function() {
        return bindEvent($(this));
      });
    }
  });

}).call(this);
